
CREATE TABLE EMP6 (
    emp_id INT,
    GBLID UNIQUEIDENTIFIER PRIMARY KEY,
    emp_name VARCHAR(50),
    emp_gender char(6),
    emp_salary MONEY,
    emp_department VARCHAR(50),
    emp_email VARCHAR(100),
    emp_address VARCHAR(100),
    emp_city VARCHAR(50),
    emp_state VARCHAR(50),
    emp_country VARCHAR(50),
    emp_phone VARCHAR(20),
    start_date DATE,
    end_date DATE
);


SELECT * FROM dbo.EMP6

DROP TABLE DBO.EMP6


SELECT DATEADD(MM, 2,GETDATE()) AS DateAdd;

SELECT DATEADD(YY, 2, '2017/08/25') AS DateAdd;


--TO FIND OUT DUPLICATE RECORDS IN THE TABLE

use EMPLOYEE;

SELECT * FROM EMP5;

SELECT empno,COUNT(empno) FROM dbo.EMP2 GROUP BY EMPNO HAVING (COUNT(empno))>1


WITH DuplicateCTE AS (
    SELECT EMPNO,
           ROW_NUMBER() OVER (PARTITION BY DEPTNO, EMPNO ORDER BY EMPNO) AS RowNumber
    FROM EMP5
)
SELECT EMPNO
FROM DuplicateCTE
WHERE RowNumber > 1;


DELETE FROM EMP5 A WHERE ROWID NOT IN (SELEXT MAX(ROWID) FROM EMP5 B WHERE A.ID=B.ID)

DELETE FROM EMP5 A 
WHERE ROWID NOT IN (SELECT MAX(ROWID) FROM EMP5 B WHERE A.ID = B.ID);







>>>>>>> 591731762cd9d3280aded8d5b3ca1797ecd3a1bf
