SELECT *  FROM EMP1
WITH HIGH_SAAL AS (
SELECT EMP1.*,DENSE_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RNK FROM EMP1
)
SELECT * FROM HIGH_SAAL WHERE RNK=3

SELECT MAX(SAL) FROM EMP1

SELECT MAX(SAL) FROM EMP1 WHERE SAL <(SELECT MAX(SAL) FROM EMP1)