--highest salary 

SELECT MAX(SAL) FROM EMPLOYEE.dbo.EMP2 --WHERE SAL < (SELECT MAX(SAL) FROM EMPLOYEE.dbo.EMP2);

--HIGHEST SALARY IN EACH DEPT

SELECT ename, sal, deptno
FROM EMPLOYEE.dbo.EMP2
WHERE SAL IN (SELECT MAX(sal) FROM EMPLOYEE.dbo.EMP2 GROUP BY deptno);

--by using dense rank

SELECT * FROM (SELECT *, DENSE_RANK() OVER (PARTITION BY deptno ORDER BY sal DESC) AS RNK 
FROM EMPLOYEE.dbo.EMP2) AS RESULT WHERE RNK=1;


--by using dense rank cte

WITH HIGH_RANK AS
(
SELECT *, DENSE_RANK() OVER (ORDER BY SAL DESC) AS RNK FROM EMPLOYEE.dbo.EMP2
)
SELECT * FROM HIGH_RANK WHERE RNK <= 5 --AND DEPTNO = 20;

--BY USING TOP 

SELECT TOP 1 SAL FROM(
SELECT DISTINCT TOP 1 SAL
FROM EMP5 
ORDER BY SAL DESC
)AS RASULT
ORDER BY SAL;

--FIND THE RANKING IN SALES DEPARTMENT

WITH CTE_EMP AS (
    SELECT 
        E.empno,
        E.ename,
        D.dname,
        DENSE_RANK() OVER (PARTITION BY D.dname ORDER BY E.sal DESC) AS rnk
    FROM EMPLOYEE.dbo.EMP2 E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
)
SELECT *
FROM CTE_EMP
WHERE rnk <= 5 AND dname = 'SALES';











