
SELECT * FROM dbo.EMP5

--THIRD HIGHEST SALARY

SELECT MAX(SAL) FROM EMP5 
WHERE SAL < (SELECT MAX(SAL) FROM EMP5
WHERE SAL < (SELECT MAX(SAL) FROM EMP5));

SELECT TOP 2 SAL FROM
(SELECT DISTINCT TOP 3 SAL FROM EMP5 ORDER BY SAL DESC) 
AS RESULT ORDER BY SAL;


WITH THIRD_HIGHEST AS (
    SELECT EMP5 .*,DENSE_RANK() OVER (ORDER BY SAL DESC ) AS RANK FROM EMP5
)
SELECT * FROM THIRD_HIGHEST
 WHERE RANK=3;


