
USE EMPLOYEE;

SELECT * FROM dbo.EMP5

select * from dbo.DEPT;

--THIRD HIGHEST SALARY

SELECT MAX(SAL) FROM EMP5 
WHERE SAL < (SELECT MAX(SAL) FROM EMP5
WHERE SAL < (SELECT MAX(SAL) FROM EMP5));

SELECT TOP 2 SAL FROM
(SELECT DISTINCT TOP 3 SAL FROM EMP5 ORDER BY SAL DESC) 
AS RESULT ORDER BY SAL;


WITH THIRD_HIGHEST AS (
    SELECT EMP5 .*,DENSE_RANK() OVER (ORDER BY SAL DESC ) AS RANK FROM EMP5
)
SELECT * FROM THIRD_HIGHEST
 WHERE RANK=3;

-- 3RD HIGHEST SALARY FROM ALL DEPARTEMENTS
 SELECT * FROM (SELECT EMP5 .*,ROW_NUMBER() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS ROW_NUMBER FROM EMP5) AS RANK
 WHERE ROW_NUMBER  < 4;


--HIGHEST SALARY FROM EMP TABLE

SELECT MAX(SAL) AS MAX_SAL,MIN(SAL) AS MIN_SAL  FROM dbo.EMP5;

--GET EMPLOYEE DETAILS WHO HAS HIGHEST SALARY

SELECT * FROM EMP5 WHERE SAL=(SELECT MAX(SAL) FROM EMP5)


--GET SECOND HIGHEST SALARY FROM EMP TABLE

SELECT * FROM EMP5 WHERE SAL=(SELECT MAX(SAL) FROM EMP5 WHERE SAL <(SELECT MAX(SAL) FROM EMP5))


SELECT TOP 2 SAL FROM(
    SELECT DISTINCT TOP 5 SAL,DEPTNO
    FROM EMP5 ORDER BY SAL DESC)
    AS RESULT ORDER BY SAL DESC;


--GET DEPATEMENT WISE HIGHEST SALARY

SELECT EMP5.*,MAX(SAL) AS MAX_SAL FROM EMP5 E JOIN DEPT D ON E.DEPTNO=D.DEPTNO GROUP BY dname;



--
CREATE TABLE SOURCEA (ID INT,NAME NVARCHAR(15),STATE NVARCHAR(10));

INSERT INTO SOURCEA VALUES(1,'A','DELHI');
INSERT INTO SOURCEA VALUES(2,'B','DELHI');
INSERT INTO SOURCEA VALUES(3,'C','NULL');
DROP TABLE SOURCEA

CREATE TABLE SOURCEB (ID INT,NAME NVARCHAR(15),STATE NVARCHAR(10));

INSERT INTO SOURCEB VALUES(1,'A','DELHI');
INSERT INTO SOURCEB VALUES(3,'C','HARIYANA');
INSERT INTO SOURCEB VALUES(4,'D','MUMBAI');
INSERT INTO SOURCEB VALUES(5,'E','NULL');

SELECT * FROM SOURCEA;
SELECT * FROM SOURCEB;



SELECT 
    CASE 
        WHEN A.ID IS NOT NULL THEN A.ID
        ELSE B.ID 
    END AS ID,
    CASE 
        WHEN A.NAME IS NOT NULL THEN A.NAME
        ELSE B.NAME
    END AS NAME,
    CASE 
        WHEN A.STATE IS NOT NULL THEN A.STATE
        ELSE B.STATE
    END AS STATE
FROM 
    SOURCEA A 
FULL OUTER JOIN 
    SOURCEB B ON A.ID = B.ID 
ORDER BY 
    CASE 
        WHEN A.ID IS NOT NULL THEN A.ID 
        ELSE B.ID 
    END;

















