

SELECT * FROM EMPLOYEES.dbo.EMP2


-- bY USING SUBQUERY

SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2

SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2
WHERE SAL < (SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2)

-- BY USING NOT IN OPERATOR

SELECT TOP 1 SAL FROM EMPLOYEES.dbo.EMP2
WHERE SAL NOT IN (SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2)
ORDER BY SAL DESC

-- BY USING OFFSET

SELECT SAL FROM EMPLOYEES.dbo.EMP2
ORDER BY SAL DESC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

SELECT SAL FROM EMPLOYEES.dbo.EMP2
ORDER BY SAL DESC
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY

-- BY USING DENSE RANK

SELECT * FROM (SELECT EMP2.*,DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK FROM EMPLOYEES.dbo.EMP2) 
RANKED_SALARY WHERE RANK=1;

SELECT * FROM (SELECT EMP2.*,DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK FROM EMPLOYEES.dbo.EMP2) RANKED_SALARY 
WHERE RANK=2;


--BY USING CTE

WITH CTE_ranksal AS
(
SELECT EMP2.*, DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK FROM EMPLOYEES.dbo.EMP2
)
SELECT * FROM CTE_ranksal 
WHERE RANK=1;

--by using top cpmmand

SELECT TOP 1 Sal
FROM (
    SELECT DISTINCT TOP 1 Sal
    FROM EMP2
    ORDER BY sal DESC
) AS RESULT
ORDER BY sal;

--BY USING NTH HIGHEST SALARY

SELECT * FROM EMPLOYEES.dbo.EMP2 E1
WHERE (2-1) = (
                SELECT COUNT(DISTINCT(E2.Sal))
                FROM EMPLOYEES.dbo.EMP2 E2
                WHERE E2.Sal > E1.Sal
              )




