--2ND HIGHEST SALARY

SELECT * FROM EMPLOYEES.dbo.EMP2


-- bY USING SUBQUERY

SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2
WHERE SAL < (SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2)

-- BY USING NOT IN OPERATOR

SELECT TOP 1 SAL FROM EMPLOYEES.dbo.EMP2
WHERE SAL NOT IN (SELECT MAX(SAL) FROM EMPLOYEES.dbo.EMP2)
ORDER BY SAL DESC

-- BY USING OFFSET

SELECT SAL FROM EMPLOYEES.dbo.EMP2
ORDER BY SAL DESC
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY

-- BY USING DENSE RANK

SELECT * FROM (SELECT EMP2.*,DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK FROM EMPLOYEES.dbo.EMP2) RANKED_SALARY 
WHERE RANK=2;

--BY USING CTE

WITH CTE AS
(
SELECT EMP2.*, DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK FROM EMPLOYEES.dbo.EMP2
)
SELECT * FROM CTE
WHERE RANK=2;

