-- finding out duplicate values in the table

SELECT * FROM EMPLOYEES.dbo.EMP2

INSERT INTO EMP2 VALUES(7844,'TURNER','SALESMAN',7698,'08-SEP-1981',1500,0,30);
INSERT INTO EMP2 VALUES(7499,'ALLEN','SALESMAN',7698,'20-FEB-1981',1600,300,30);


-- by using cte

WITH duplicate_cte AS
(
SELECT *, ROW_NUMBER() OVER(PARTITION BY EMPNO ORDER BY EMPNO) AS RN
FROM EMP2
)
SELECT * FROM duplicate_cte WHERE RN > 1;


-- by using count 

SELECT EMPNO,COUNT(EMPNO) FROM EMPLOYEES.dbo.EMP2 GROUP BY EMPNO HAVING (COUNT(EMPNO)) >1;

-- BY USING ROWID IN  ORACLE DATABSE
SELECT * FROM EMPLOYEES.dbo.EMP2 E1 WHERE ROWID NOT IN (SELECT MAX(ROWID) FROM EMPLOYEES.dbo.EMP2 E2 
WHERE E1.EMPNO=E2.EMPNO GROUP BY E2.EMPNO); 