SELECT * FROM EMPLOYEES.dbo.EMP2

-- find out 5th row from emp2 table
SELECT * FROM(SELECT EMP2.*,ROW_NUMBER() OVER ( ORDER BY EMPNO) AS ROWNUM
FROM EMPLOYEES.dbo.EMP2) RANKED_ROWNUM
WHERE ROWNUM <= 5
EXCEPT
SELECT * FROM(SELECT EMP2.*,ROW_NUMBER() OVER ( ORDER BY EMPNO) AS ROWNUM
FROM EMPLOYEES.dbo.EMP2) RANKED_ROWNUM
WHERE ROWNUM <= 4;

-- FIRST_NAME AND LAST_NAME FROM FULL_NAME 

CREATE TABLE EMP1(
EMPNO INT,
FULL_NAME VARCHAR(20),
JOB VARCHAR(20),
MGR INT,
HIREDATE DATE,
SAL INT,
COMM INT,
DEPTNO INT
);

INSERT EMP1 VALUES(7369,'MAHESH KSHIRSAGAR','CLERK',7902,'17-DEC-1980',800,NULL,20);
INSERT EMP1 VALUES(7499, 'GAGAN PANDEY', 'SALESMAN', 7698, '20-FEB-1981', 1600, 300, 30);
INSERT EMP1 VALUES(7521, 'ROHIT SHARMA', 'SALESMAN', 7698, '22-FEB-1981', 1250, 500, 30);
INSERT EMP1 VALUES(7566, 'SACHIN TENDULKAR', 'MANAGER', 7839, '2-APR-1981', 2975, NULL, 20);
INSERT EMP1 VALUES(7654, 'MUKESH AMBANI', 'SALESMAN', 7698, '28-SEP-1981', 1250, 1400, 30);
INSERT EMP1 VALUES(7698, 'MANOJ PANDIT', 'MANAGER', 7839, '1-MAY-1981', 2850, NULL, 30);
INSERT EMP1 VALUES(7782, 'ANIL KUMAR', 'CLERK', 7839, '9-NOV-1982', 2450, NULL, 10);
INSERT EMP1 VALUES(7788, 'SANJAY SHARMA', 'ANALYST', 7566, '3-DEC-1982', 3000, NULL, 20);

SELECT * FROM EMPLOYEES.dbo.EMP1;

DROP TABLE EMPLOYEES.dbo.EMP1;

--FIRST_NAME AND LAST_NAME
SELECT FULL_NAME,LEFT(FULL_NAME, CHARINDEX(' ', FULL_NAME) - 1) AS FIRST_NAME,
RIGHT(FULL_NAME, LEN(FULL_NAME) - CHARINDEX(' ', FULL_NAME)) AS LAST_NAME
FROM EMP1;

--BY USING STRING_SPLIT FUNCTION

USE EMPLOYEES;

WITH
    NAME_CTE
    AS
    (
        SELECT EMPNO, VALUE,
            ROW_NUMBER() OVER (PARTITION BY EMPNO ORDER BY EMPNO) AS Rownum
        from EMPLOYEES.dbo.EMP1
CROSS APPLY
string_split(FULL_NAME,' ')
    )
SELECT EMPNO,
    [1] AS FIRST_NAME, [2] AS LAST_NAME
FROM NAME_CTE
PIVOT
(MAX(VALUE)
for Rownum in ([1],[2])) as PVT;


-- BY USING ORACLE DATABASE

SELECT
    EMPNO,
    SUBSTR(FULL_NAME, 1, INSTR(FULL_NAME, ' ') - 1) AS FIRST_NAME,
    SUBSTR(FULL_NAME, INSTR(FULL_NAME, ' ') + 1) AS LAST_NAME
FROM EMP1;



