

SELECT SUBSTRING(EMAIL,1,3) AS F_NAME,SUBSTRING(EMAIL,5,3) AS SECOND,
SUBSTRING(EMAIL,9,5) AS ORGNAME,SUBSTRING(EMAIL,1,-3) AS EXT FROM employee2;


SELECT SUBSTRING(EMAIL,1,INSTRING(EMAIL'.')-1) AS FIRST,







SELECT * FROM employee2