

USE EMPLOYEE;

--TO FIND OUT DUPLICATE RECORDS IN THE TABLE

SELECT empno,COUNT(empno) FROM dbo.EMP2 GROUP BY EMPNO HAVING (COUNT(empno))>1


--by using cte find out duplicates
WITH CTE AS
(
SELECT *,ROW_NUMBER() OVER(PARTITION BY EMPNO ORDER BY EMPNO) AS RN
FROM dbo.EMP2
)
SELECT * FROM CTE WHERE RN>1

--delete duplicate records from the table by using cte

WITH CTE AS
(
SELECT *,ROW_NUMBER() OVER(PARTITION BY EMPNO ORDER BY EMPNO) AS RN
FROM dbo.EMP2
)
DELETE FROM CTE WHERE RN>1

SELECT * FROM dbo.EMP2



-- DELETE THE DUPLICATE RECORDS FROM THE TABLE

DELETE FROM dbo.EMP2 A WHERE ROWID NOT IN (SELECT MAX(ROWID) FROM dbo.EMP2 B WHERE A.empno=B.empno)