
--2ND HIGHEST SALARY 
SELECT * FROM EMP2
--
SELECT TOP 1 Sal FROM
(SELECT DISTINCT TOP 2 Sal
FROM EMP2
ORDER BY sal DESC) 
RESULT
ORDER BY sal

--
SELECT max(sal) from EMP2 WHERE sal<(SELECT max(sal) from EMP2)

--
WITH MAX_2SAL AS (
    SELECT empno, ename, job, DENSE_RANK() OVER (ORDER BY SAL DESC) AS RANK 
    FROM EMP2
)
SELECT empno, ename, job
FROM MAX_2SAL 
WHERE RANK = 2;
