
--2ND HIGHEST SALARY 
SELECT * FROM EMP2
--
SELECT TOP 1 Sal FROM
(SELECT DISTINCT TOP 2 Sal
FROM EMP2
ORDER BY sal DESC) 
RESULT
ORDER BY sal

--
SELECT max(sal) from EMP2 WHERE sal<(SELECT max(sal) from EMP2)

--
WITH MAX_2SAL AS (
    SELECT  DENSE_RANK() OVER (ORDER BY sal DESC) AS RANK 
    FROM EMP2
) t
SELECT *
FROM MAX_2SAL 
WHERE t.RANK = 2;
