

USE EMPLOYEE;

DROP TABLE SRC_EMP;

--SCD1
create table SRC_EMP
(EMP_ID INT,
EMP_NAME VARCHAR(20),
STATE VARCHAR(20))


INSERT INTO SRC_EMP VALUES(1001,'ALAN','NY');
INSERT INTO SRC_EMP VALUES(1002,'BOB','CHICAGO');
INSERT INTO SRC_EMP VALUES(1003,'GEORGE','LA');


UPDATE SRC_EMP SET STATE='CHICAGO' WHERE EMP_ID=1003;


CREATE TABLE DIM_EMP_SCD
(EMP_ID INT,
EMP_NAME VARCHAR(20),
STATE VARCHAR(20));


SELECT * FROM SRC_EMP;

SELECT * FROM DIM_EMP_SCD;

DELETE DIM_EMP_SCD;

---------
--SCD2

CREATE TABLE DIM_EMP_SCD2_DATE
(EMP_ID INT,
EMP_NAME VARCHAR(20),
STATE VARCHAR(20),
START_DATE_ DATETIME,
END_DATE_  DATETIME);

Delete DIM_EMP_SCD2_DATE;

SELECT * FROM SRC_EMP;

SELECT * FROM DIM_EMP_SCD2_DATE;


UPDATE SRC_EMP SET STATE='LA' WHERE EMP_ID=1003;


--SCD TYPE 2 WITH STATUS

CREATE TABLE DIM_EMP_SCD2_STATUS
(EMP_ID INT,
EMP_NAME VARCHAR(20),
STATE VARCHAR(20),
CURRENT_SATUS VARCHAR(20)
);

Delete DIM_EMP_SCD2_DATE;

DROP TABLE DIM_EMP_SCD2_STATUS;

SELECT * FROM SRC_EMP;

SELECT * FROM DIM_EMP_SCD2_STATUS


UPDATE SRC_EMP SET STATE='CHICAGO' WHERE EMP_ID=1003;



