--WRITE A SQL QUERY TO PRINT MOVIE THEATHER SEATING ARRAGEMENT.


WITH CTE_ALPHABET AS(
    SELECT CHAR(ASCII('A')) AS LETTER
    UNION ALL
    SELECT CHAR(ASCII(LETTER)+1) FROM CTE_ALPHABET WHERE LETTER != 'L'
),
CTE_SEAT AS(
    SELECT 1 AS NBR
    UNION ALL
    SELECT NBR+1 FROM CTE_SEAT WHERE NBR <=10
),
CTE_FINAL AS(
    SELECT LETTER,LETTER + TRIM(STR(NBR)) AS SEAT_NO FROM CTE_ALPHABET CROSS JOIN CTE_SEAT

)
SELECT LETTER AS ROW,STRING_AGG(SEAT_NO,',') WITHIN GROUP (ORDER BY LETTER) FROM CTE_FINAL GROUP BY LETTER
