USE OTHERS

CREATE TABLE TABLE_FIRST(X INT);
CREATE TABLE TABLE_SECOND(Y INT);

INSERT INTO TABLE_FIRST VALUES(9);
INSERT INTO TABLE_FIRST VALUES(8);
INSERT INTO TABLE_FIRST VALUES(NULL);

INSERT INTO TABLE_SECOND VALUES(9);
INSERT INTO TABLE_SECOND VALUES(9);
INSERT INTO TABLE_SECOND VALUES(NULL);

SELECT * FROM TABLE_FIRST;

SELECT * FROM TABLE_SECOND;

--INNER JOIN 
SELECT X,Y FROM TABLE_FIRST F INNER JOIN TABLE_SECOND S ON F.X=S.Y

--LEFT OUTER JOIN

SELECT X,Y FROM TABLE_FIRST F LEFT OUTER JOIN TABLE_SECOND S ON F.X=S.Y


--RIGHT OUTER JOIN

SELECT X,Y FROM TABLE_FIRST F RIGHT OUTER JOIN TABLE_SECOND S ON F.X=S.Y

--FULL OUTER JOIN

SELECT X,Y FROM TABLE_FIRST F FULL OUTER JOIN TABLE_SECOND S ON F.X=S.Y






