-- WRITE SQL TO PRINT ALL THE LETTERS OF ENGLISH ALPHABETS


SELECT CHAR(90)
SELECT ASCII('A')


WITH ALPHABET AS
(
    SELECT CHAR(ASCII('A')) AS LETTER   --ANCHOR QUERY
    UNION ALL
    SELECT CHAR(ASCII(LETTER)+1)     -- RECURSIVE PART
    FROM ALPHABET
    WHERE LETTER <> 'Z'
)

SELECT * FROM ALPHABET;

-- ALLPHABET AA RESULT  

SELECT * FROM SYS.COLUMNS

WITH ALPHABET_CTE AS
(SELECT ROW_NUMBER() OVER (ORDER BY OBJECT_ID) AS ALP FROM SYS.COLUMNS)

SELECT CHAR(((ALP-1)/26)+65) + CHAR(65 + (ALP-1) % 26) FROM ALPHABET_CTE
WHERE ALP <=676

--ALPHABET AAA RESULT  

WITH ALPHABET_CTE AS
(SELECT ROW_NUMBER() OVER (ORDER BY OBJECT_ID) AS ALP FROM SYS.COLUMNS)

SELECT CHAR(((ALP-1)/26)+65) + CHAR(65 + (ALP-1) % 26)+ CHAR(65 + (ALP-1) % 26) FROM ALPHABET_CTE
WHERE ALP <=676




