USE STUDENTS

CREATE TABLE STUDENTINFO(StudentName nvarchar(20),ENGLISH INT,MATHS INT,SCIENCE INT);

INSERT INTO STUDENTINFO VALUES('DAVID',85,90,88);
INSERT INTO STUDENTINFO VALUES('JOHN',70,85,80);
INSERT INTO STUDENTINFO VALUES('TOM',83,80,92);

SELECT * FROM dbo.STUDENTINFO;

--unpivot operator

SELECT StudentName,SUBJECTS,MARKS
FROM
(
    SELECT StudentName,ENGLISH,MATHS,SCIENCE FROM STUDENTINFO
) A
UNPIVOT
(
    MARKS FOR SUBJECTS IN (ENGLISH,MATHS,SCIENCE)
) AS UNPVT


--BY USING UNION ALL

SELECT StudentName,'ENGLISH' AS SUBJECTS,ENGLISH AS'MARKS' FROM STUDENTINFO
UNION ALL
SELECT StudentName,'MATHS',MATHS FROM STUDENTINFO
UNION ALL
SELECT StudentName,'SCIENCE',SCIENCE FROM STUDENTINFO
ORDER BY StudentName;