--How to capitalize first letter of a string

CREATE PROCEDURE INITCAP
AS

BEGIN


CREATE TABLE NAME(ENAME CHAR(15))

INSERT INTO NAME VALUES('shankar')
INSERT INTO NAME VALUES('sarika')
INSERT INTO NAME VALUES('mahadev')

INSERT INTO NAME VALUES('karuna')
INSERT INTO NAME VALUES('amrapali')
INSERT INTO NAME VALUES('amita')

INSERT INTO NAME VALUES('shivani')
INSERT INTO NAME VALUES('kamini')
INSERT INTO NAME VALUES('parul')

INSERT INTO NAME VALUES('samar')
INSERT INTO NAME VALUES('renuka')
INSERT INTO NAME VALUES('shruthi')

INSERT INTO NAME VALUES('kavita')
INSERT INTO NAME VALUES('kavya')
INSERT INTO NAME VALUES('shabnam')

SELECT * from NAME;

SELECT ENAME,UPPER(LEFT(ENAME,1)) + SUBSTRING(ENAME,2,LEN(ENAME)) AS EMP_NAME
FROM dbo.NAME

END


EXEC INITCAP
