CREATE TABLE TAB1(C1 VARCHAR(1));
CREATE TABLE TAB2(C1 VARCHAR(1));

INSERT INTO TAB1 VALUES('A');
INSERT INTO TAB1 VALUES('B');
INSERT INTO TAB1 VALUES('C');
INSERT INTO TAB1 VALUES('D');
INSERT INTO TAB1 VALUES('E');


INSERT INTO TAB2 VALUES('A');
INSERT INTO TAB2 VALUES('C');
INSERT INTO TAB2 VALUES('E');
INSERT INTO TAB2 VALUES('G');

COMMIT;


SELECT * FROM TAB1;
SELECT * FROM TAB2;
