CREATE TABLE TAB1(C1 VARCHAR(1));
CREATE TABLE TAB2(C1 VARCHAR(1));

INSERT INTO TAB1 VALUES('A');
INSERT INTO TAB1 VALUES('B');
INSERT INTO TAB1 VALUES('C');
INSERT INTO TAB1 VALUES('D');
INSERT INTO TAB1 VALUES('E');


INSERT INTO TAB2 VALUES('A');
INSERT INTO TAB2 VALUES('C');
INSERT INTO TAB2 VALUES('E');
INSERT INTO TAB2 VALUES('G');

COMMIT;


SELECT * FROM TAB1;
SELECT * FROM TAB2;


--Method 1

SELECT * FROM TAB1
MINUS
SELECT * FROM TAB2;

--Method 2

SELECT * FROM TAB1 WHERE 1 > (SELECT COUNT(*) FROM TAB2 WHERE TAB1.C1=TAB2.C1);

--Method 3

SELECT * FROM TAB1 LEFT OUTER JOIN TAB2 ON TAB1.C1=TAB2.C1 WHERE TAB2.C1 IS NULL;

--Method 4

SELECT C1 FROM TAB1 WHERE (SELECT COUNT(1) FROM TAB2 WHERE TAB2.C1=TAB1.C1)=0;



