SELECT 'WELCOME' FROM DUAL CONNECT BY LEVEL <=LENGTH('WELCOME');

 --OTPUT 1

SELECT ROWNUM,

    SUBSTR(S,ROWNUM,1) AS OUTPUT1,

    SUBSTR(S,ROWNUM*-1,1) AS OUTPUT2,

    SUBSTR(S,1,ROWNUM) AS OUTPUT3,

    SUBSTR(S,ROWNUM) AS OUTPUT4,

    RPAD(' ',ROWNUM,' ')||SUBSTR(S,ROWNUM) AS OUTPUT5,

    RPAD(' ',LENGTH(S)+1-ROWNUM,' ')||SUBSTR(S,1,ROWNUM) AS OUTPUT6

FROM DUAL,(SELECT 'WELCOME' AS S FROM DUAL)
CONNECT BY LEVEL <=LENGTH(S);







