CREATE TABLE SERVICE(SERVICE_CODE VARCHAR2(1),SERVICE_NAME VARCHAR2(20));

INSERT INTO SERVICE (SERVICE_CODE,SERVICE_NAME) VALUES('A','Service-A');
INSERT INTO SERVICE (SERVICE_CODE,SERVICE_NAME) VALUES('B','Service-B');
INSERT INTO SERVICE (SERVICE_CODE,SERVICE_NAME) VALUES('C','Service-C');
INSERT INTO SERVICE (SERVICE_CODE,SERVICE_NAME) VALUES('D','Service-D');

SELECT * FROM SERVICE;

-- Create the SERVICE_PRODUCT table

CREATE TABLE SERVICE_PRODUCT(PRODUCT_CODE VARCHAR2(2),PRDUCT_DESC VARCHAR2(10),SERVICE_ORDER VARCHAR(15));

-- Insert data into the SERVICE_PRODUCT table
INSERT INTO SERVICE_PRODUCT VALUES ('P1', 'PROD-P1', 'A,C');
INSERT INTO SERVICE_PRODUCT VALUES ('P2', 'PROD-P2', 'C,B,D');
INSERT INTO SERVICE_PRODUCT VALUES ('P3', 'PROD-P3', 'D,A,C,B');
INSERT INTO SERVICE_PRODUCT VALUES ('P4', 'PROD-P4', 'A,B,C,D');
INSERT INTO SERVICE_PRODUCT VALUES ('P5', 'PROD-P5', 'D,C,B,A,B');


SELECT * FROM SERVICE_PRODUCT;
DROP TABLE SERVICE_PRODUCT;

SELECT PRODUCT_CODE,PRDUCT_DESC,SERVICE_ORDER,l,
        REGEXP_SUBSTR(SERVICE_ORDER,'(.*?,) {' ||(1-1) ||'}([^,]*)',1,1,' ',2 )
FROM SERVICE_PRODUCT,
        LATERAL(SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= REGR_COUNT(SERVICE_ORDER,',')+1);
