CREATE TABLE CRICKET (MATCHNO NUMBER,TEAM_A VARCHAR(15),TEAM_B VARCHAR(15),WINNER VARCHAR(15));


INSERT INTO CRICKET VALUES(1,'WESTINDIES','SRILANKA','WESTINDIES');

INSERT INTO CRICKET VALUES(2,'INDIA','SRILANKA','INDIA');

INSERT INTO CRICKET VALUES(3,'AUSTRALIA','SRILANKA','AUSTRALIA');

INSERT INTO CRICKET VALUES(4,'WESTINDIES','SRILANKA','SRILANKA');

INSERT INTO CRICKET VALUES(5,'AUSTRALIA','INDIA','AUSTRALIA');

INSERT INTO CRICKET VALUES(6,'INDIA','WESTINDIES','WESTINDIES');

INSERT INTO CRICKET VALUES(7,'INDIA','WESTINDIES','WESTINDIES');

INSERT INTO CRICKET VALUES(8,'WESTINDIES','AUSTRALIA','AUSTRALIA');

INSERT INTO CRICKET VALUES(9,'WESTINDIES','INDIA','INDIA');

INSERT INTO CRICKET VALUES(10,'AUSTRALIA','WESTINDIES','WESTINDIES');

INSERT INTO CRICKET VALUES(11,'WESTINDIES','SRILANKA','WESTINDIES');

INSERT INTO CRICKET VALUES(12,'INDIA','AUSTRALIA','INDIA');

INSERT INTO CRICKET VALUES(13,'SRILANKA','NEWZEALAND','SRILANKA');

INSERT INTO CRICKET VALUES(14,'NEWZEALAND','INDIA','INDIA');


SELECT * FROM CRICKET;

drop table CRICKET;


WITH MATCHES_PLAYED AS(
    SELECT TEAM_NAME,
    COUNT(*) as cnt
    FROM (
            SELECT TEAM_A TEAM_NAME 
            FROM CRICKET 
            UNION ALL 
            SELECT TEAM_B 
            FROM CRICKET)
            GROUP BY TEAM_NAME),
MATCHES_WON AS(SELECT WINNER,
            COUNT(*) AS cnt
            FROM CRICKET 
            GROUP BY WINNER)
SELECT TEAM_NAME,
        MATCHES_PLAYED.cnt AS TOTAL_MATCHES,
        NVL(MATCHES_WON.cnt,0) AS MATCHES_WON,
        MATCHES_PLAYED.cnt - NVL(MATCHES_WON.cnt,0) AS MATCHES_LOST
FROM MATCHES_PLAYED 
FULL OUTER JOIN MATCHES_WON 
ON MATCHES_PLAYED.TEAM_NAME = MATCHES_WON.WINNER;