 
 --generate 1 to 10 sequence
 --METHID 1
 SELECT ROWNUM
 FROM EMP E WHERE ROWNUM < =10;

--METHOD 2
 SELECT ROWNUM,LEVEL FROM DUAL
 CONNECT BY LEVEL <=10;

 --METHOD 3

CREATE OR REPLACE FUNCTION FN_GET_TABLE_OF_NUMBERS(P_COUNT NUMBER) RETURN SYS.ODCINUMBERLIST IS
    NUM_TAB SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
BEGIN
    FOR I IN 1 .. P_COUNT LOOP
        NUM_TAB.EXTEND;
        NUM_TAB(NUM_TAB.LAST) := I;
    END LOOP;

    RETURN NUM_TAB;
END FN_GET_TABLE_OF_NUMBERS;
/

SELECT * FROM TABLE(FN_GET_TABLE_OF_NUMBERS(10));


--METHOD 4

WITH T1 (ID) AS(
    SELECT 1 ID 
    FROM DUAL 
    UNION ALL
    SELECT ID+1 
    FROM T1
    WHERE ID<10
)
SELECT ID FROM T1;

--XML TABLE
SELECT ROWNUM 
FROM XMLTABLE('1 TO 10');







      
 