SELECT * FROM EMP4

--QUE -EMPLOYEES HAVING HIGHEST SALARY IN THE DPATEMENT


SELECT EMPKEY,FIRST_NAME,LAST_NAME,EM.EMP_DEPT,EMP_SALARY FROM EMP4 EM

INNER JOIN

(SELECT EMP_DEPT,MAX(EMP_SALARY) AS MAX FROM EMP4 GROUP BY EMP_DEPT) AS MAXSALEMP

ON

EM.EMP_DEPT=MAXSALEMP.EMP_DEPT AND
EM.EMP_SALARY=MAXSALEMP.MAX


    -- BY USING ANALYTICAL FUNCTION

SELECT * FROM
(SELECT EMPKEY,FIRST_NAME,LAST_NAME,EMP_DEPT,EMP_SALARY,
RANK () OVER (PARTITION BY EMP_DEPT ORDER BY EMP_SALARY DESC) AS MAXSAL
 FROM EMP4) AS EM
 WHERE EM.MAXSAL =1


 --QUERY
 -- EMPLOYEES HAVING GREATER THAN AVG SALARY OF THE DEPARTEMENT

 SELECT EMPKEY, FIRST_NAME, LAST_NAME, EM.EMP_DEPT, EMP_SALARY 
FROM EMP4 EM
INNER JOIN (
    SELECT EMP_DEPT, AVG(EMP_SALARY) AS AVGSAL 
    FROM EMP4 
    GROUP BY EMP_DEPT
) AS AVGEMPSAL
ON EM.EMP_DEPT = AVGEMPSAL.EMP_DEPT
AND EM.EMP_SALARY > AVGEMPSAL.AVGSAL;



 --QUERY
 -- EMPLOYEES HAVING GREATER THAN AVG SALARY OF THE DEPARTEMENT BUT LESS 
 -- THAN THE OVERALL AVERAGE

  SELECT EMPKEY, FIRST_NAME, LAST_NAME, EM.EMP_DEPT, EMP_SALARY 
FROM EMP4 EM
INNER JOIN (
    SELECT EMP_DEPT, AVG(EMP_SALARY) AS AVGSAL 
    FROM EMP4 
    GROUP BY EMP_DEPT
) AS AVGEMPSAL
ON EM.EMP_DEPT = AVGEMPSAL.EMP_DEPT
AND EM.EMP_SALARY > AVGEMPSAL.AVGSAL
AND EM.EMP_SALARY < (SELECT  AVG(EMP_SALARY) FROM EMP4)

 
 
 
 --WRITE A QUERY EMPLOYEES  SALARY HAVING GREATER THAN THEIR MANAGER'S SALARY

SELECT EMPKEY, FIRST_NAME, LAST_NAME,EMP_DEPT, EMP_SALARY 
FROM EMP4 EM WHERE EMP_SALARY > (SELECT EMP_SALARY FROM EMP4 WHERE EMPKEY=EM.MGR_KEY)

select * from EMP4


SELECT EM.EMPKEY, FIRST_NAME, LAST_NAME,EMP_DEPT, EMP_SALARY ,MGR_NAME,MGR_SAL FROM EMP4 EM
JOIN
(SELECT EMPKEY,FIRST_NAME+' '+LAST_NAME AS MGR_NAME,EMP_SALARY AS MGR_SAL FROM EMP4) AS MGR

ON

EM.MGR_KEY= MGR.EMPKEY

AND

EM.EMP_SALARY > MGR.MGR_SAL


SELECT EM.EMPKEY, EM.FIRST_NAME, EM.LAST_NAME, EM.EMP_DEPT, EM.EMP_SALARY,
       MGR.FIRST_NAME + ' ' + MGR.LAST_NAME AS MGR_NAME, MGR.EMP_SALARY AS MGR_SAL 
FROM EMP4 EM
 INNER JOIN EMP4 MGR ON EM.MGR_KEY = MGR.EMPKEY
WHERE EM.EMP_SALARY > MGR.EMP_SALARY;


--QUERY EMPLOYEES INCREMENTED SALRY IF THEY HAVE COMEPLETED 30 YEARS WITH THE ORGANISATION






 


