SELECT * FROM EMP4

--QUE -EMPLOYEES HAVING HIGHEST SALARY IN THE DPATEMENT


SELECT EMPKEY,FIRST_NAME,LAST_NAME,EM.EMP_DEPT,EMP_SALARY FROM EMP4 EM

INNER JOIN

(SELECT EMP_DEPT,MAX(EMP_SALARY) AS MAX FROM EMP4 GROUP BY EMP_DEPT) AS MAXSALEMP

ON

EM.EMP_DEPT=MAXSALEMP.EMP_DEPT AND
EM.EMP_SALARY=MAXSALEMP.MAX


    -- BY USING ANALYTICAL FUNCTION

SELECT * FROM
(SELECT EMPKEY,FIRST_NAME,LAST_NAME,EMP_DEPT,EMP_SALARY,
RANK () OVER (PARTITION BY EMP_DEPT ORDER BY EMP_SALARY DESC) AS MAXSAL
 FROM EMP4) AS EM
 WHERE EM.MAXSAL =1


