--Generate the container series of alpabet

SELECT * FROM SYS.COLUMNS

WITH ALPHABET_CTE AS
(SELECT ROW_NUMBER() OVER (ORDER BY OBJECT_ID) AS ALP FROM SYS.COLUMNS)


SELECT CHAR(((ALP-1)/26)+65) + CHAR(65 + (ALP-1) % 26) FROM ALPHABET_CTE
WHERE ALP <=676



 

