



--TO FIND OUT DUPLICATE RECORDS IN THE TABLE

SELECT EMPN0,COUNT(EMPNO) FROM EMP GROUP BY EMPNO HAVING COUNT(EMPNO)>1


-- DELETE THE DUPLICATE RECORDS FROM THE TABLE

DELETE FROM EMP A WHERE ROWID != (SELECT MAX(ROWID) FROM EMP B WHERE A.EMPNO=B.EMPNO)